# -*- coding: utf-8 -*-
"""Generate comprehensive test case & bug report Excel for Sports4Life DATN project."""

from datetime import date
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

OUTPUT = "TEST-CASE-Sports4Life.xlsx"
PROJECT = "Sports4Life - Website bán đồ thể thao"
VERSION = "1.0"
TEST_DATE = date.today().isoformat()

# ---------------------------------------------------------------------------
# BUG REPORT DATA (verified from code review)
# ---------------------------------------------------------------------------
BUGS = [
    {
        "id": "BUG-001",
        "module": "Thanh toán / Checkout",
        "feature": "Xác nhận đơn hàng - MoMo/Techcombank",
        "severity": "Critical",
        "title": "MoMo/Techcombank tự đánh dấu PAID khi tạo đơn",
        "detail": "Backend set paymentStatus=PAID ngay khi user chọn MOMO hoặc TECHCOMBANK và bấm xác nhận, không qua cổng thanh toán thực tế.",
        "steps": "1. Đăng nhập\n2. Thêm SP vào giỏ, checkout\n3. Chọn MoMo hoặc Techcombank\n4. Bấm 'Tôi đã thanh toán' / xác nhận",
        "expected": "paymentStatus=UNPAID cho đến khi cổng thanh toán xác nhận",
        "actual": "paymentStatus=PAID ngay lập tức",
        "files": "CheckoutServiceImpl.java (resolvePaymentStatus ~360-368)",
        "fix": "Chỉ set PAID qua callback/IPN thật; MoMo/Techcombank giữ UNPAID hoặc tích hợp gateway.",
    },
    {
        "id": "BUG-002",
        "module": "Thanh toán / SePay",
        "feature": "Trừ tồn kho khi checkout",
        "severity": "Critical",
        "title": "Trừ stock trước khi SePay xác nhận thanh toán",
        "detail": "createOrderDetails() trừ quantity variant ngay khi tạo đơn. Nếu user hủy tại cổng SePay, stock không được hoàn.",
        "steps": "1. Chọn SePay\n2. Xác nhận đơn\n3. Thoát/hủy tại cổng SePay",
        "expected": "Chưa trừ kho hoặc tự hoàn kho khi hủy/timeout",
        "actual": "Stock đã bị trừ, đơn UNPAID vẫn giữ",
        "files": "CheckoutServiceImpl.java (~119,227-243); SePayServiceImpl.java",
        "fix": "Trừ kho khi PAID; hoặc job hủy đơn UNPAID sau N phút + restock.",
    },
    {
        "id": "BUG-003",
        "module": "Thanh toán / SePay",
        "feature": "Webhook IPN SePay",
        "severity": "Critical",
        "title": "IPN SePay không đối chiếu số tiền",
        "detail": "Chỉ kiểm tra secret header và invoice; không so sánh order_amount với order.totalAmount.",
        "steps": "1. Tạo đơn 500.000đ\n2. Gửi IPN giả với amount khác (có secret hợp lệ)",
        "expected": "Từ chối IPN nếu amount không khớp",
        "actual": "Có thể đánh dấu PAID dù amount sai",
        "files": "SePayServiceImpl.java (~119-156)",
        "fix": "So sánh payload amount với order.getTotalAmount() trước khi PAID.",
    },
    {
        "id": "BUG-004",
        "module": "Bảo mật / Cấu hình",
        "feature": "Quản lý secret",
        "severity": "Critical",
        "title": "Secret production lưu plaintext trong application.properties",
        "detail": "SePay live key, Google OAuth secret, Cloudinary secret commit trong file cấu hình local.",
        "steps": "Mở src/main/resources/application.properties",
        "expected": "Secret qua biến môi trường, không commit repo",
        "actual": "Secret plaintext trong file (cần rotate ngay)",
        "files": "application.properties; .gitignore",
        "fix": "Xoay toàn bộ secret; dùng env vars; chỉ giữ .example trong repo.",
    },
    {
        "id": "BUG-005",
        "module": "Checkout / Tồn kho",
        "feature": "Đặt hàng đồng thời",
        "severity": "Critical",
        "title": "Race condition oversell tồn kho",
        "detail": "ensureStock() đọc quantity không lock; 2 request đồng thời có thể pass khi chỉ còn 1 SP.",
        "steps": "1. SP còn 1\n2. 2 tab checkout cùng lúc\n3. Cả 2 bấm xác nhận",
        "expected": "1 thành công, 1 báo hết hàng",
        "actual": "Cả 2 có thể thành công",
        "files": "CheckoutServiceImpl.java (~269-285)",
        "fix": "Pessimistic lock hoặc UPDATE quantity WHERE quantity >= ? atomic.",
    },
    {
        "id": "BUG-006",
        "module": "Sản phẩm / Checkout",
        "feature": "Giảm giá hạng thành viên",
        "severity": "High",
        "title": "Giá thành viên chỉ hiển thị FE, backend không áp dụng",
        "detail": "ProductDetailView tính memberPrice theo rankDiscountPercent; CheckoutServiceImpl dùng variant.getPrice() gốc.",
        "steps": "1. User có hạng giảm 10%\n2. Xem chi tiết SP (giá đã giảm)\n3. Checkout và xác nhận",
        "expected": "Đơn tính giá đã giảm theo hạng",
        "actual": "Đơn tính giá gốc, user thấy chênh lệch",
        "files": "ProductDetailView.vue (~450-454); CheckoutServiceImpl.java (~214-224)",
        "fix": "Áp rank discount trong calculateSubTotal() hoặc bỏ hiển thị giảm trên FE.",
    },
    {
        "id": "BUG-007",
        "module": "Giỏ hàng",
        "feature": "Giỏ theo tài khoản",
        "severity": "High",
        "title": "Giỏ localStorage không tách theo user",
        "detail": "Key cart chung 'sport-store-cart'; login user khác vẫn thấy giỏ cũ.",
        "steps": "1. User A thêm hàng\n2. Logout, User B login cùng browser",
        "expected": "Giỏ riêng theo tài khoản",
        "actual": "User B thấy giỏ của User A",
        "files": "appStore.js (~5-7, 293-331)",
        "fix": "Key cart theo username hoặc clear/sync khi login/logout.",
    },
    {
        "id": "BUG-008",
        "module": "Thanh toán / SePay",
        "feature": "Clear giỏ sau checkout",
        "severity": "High",
        "title": "Xóa giỏ trước khi redirect SePay",
        "detail": "clearCart() gọi trước submitSePayForm(); nếu hủy tại cổng user mất giỏ.",
        "steps": "1. Checkout SePay OK\n2. Hủy tại cổng thanh toán",
        "expected": "Giỏ còn để thử lại",
        "actual": "Giỏ đã bị xóa",
        "files": "PaymentView.vue (~530-533)",
        "fix": "Chỉ clearCart sau IPN PAID hoặc trang success xác nhận.",
    },
    {
        "id": "BUG-009",
        "module": "Chat / Bảo mật",
        "feature": "WebSocket JWT",
        "severity": "High",
        "title": "WebSocket chấp nhận refresh/reset token",
        "detail": "JwtStompChannelInterceptor chỉ validate expiry, không kiểm tra typ=access.",
        "steps": "CONNECT WebSocket với refresh token",
        "expected": "Từ chối, chỉ chấp nhận access token",
        "actual": "Có thể connect với refresh token",
        "files": "JwtStompChannelInterceptor.java (~67-70); JwtAuthFilter.java",
        "fix": "Thêm jwtService.isAccessToken(claims) trên CONNECT.",
    },
    {
        "id": "BUG-010",
        "module": "Chat / Bảo mật",
        "feature": "WebSocket handshake",
        "severity": "High",
        "title": "JWT lộ trong URL WebSocket query param",
        "detail": "SockJS connect với ?access_token=... trong URL, lộ qua log/proxy.",
        "steps": "DevTools → Network → WS handshake",
        "expected": "Token chỉ trong STOMP Authorization header",
        "actual": "Token trong URL query string",
        "files": "chatSocket.js (~50)",
        "fix": "Bỏ query param; chỉ gửi token qua header CONNECT.",
    },
    {
        "id": "BUG-011",
        "module": "Đăng nhập OAuth",
        "feature": "Google OAuth callback",
        "severity": "High",
        "title": "Token JWT lộ trong URL hash sau OAuth",
        "detail": "Redirect /login#accessToken=...&refreshToken=... sau Google login.",
        "steps": "Đăng nhập Google, xem URL browser",
        "expected": "Token không hiện trên URL",
        "actual": "Token trong hash URL (history, referrer leak)",
        "files": "OAuth2LoginSuccessHandler.java (~87-92)",
        "fix": "Exchange code qua POST endpoint; set token qua memory/session.",
    },
    {
        "id": "BUG-012",
        "module": "Checkout / Tồn kho",
        "feature": "Validate stock",
        "severity": "High",
        "title": "quantity=null coi như không giới hạn",
        "detail": "ensureStock() skip validation khi variant.quantity == null.",
        "steps": "Variant quantity null, đặt số lượng lớn",
        "expected": "Từ chối hoặc coi stock=0",
        "actual": "Cho phép đặt không giới hạn",
        "files": "CheckoutServiceImpl.java (~269-275)",
        "fix": "Coi null là 0; NOT NULL constraint trên DB.",
    },
    {
        "id": "BUG-013",
        "module": "Checkout / Tồn kho",
        "feature": "Trừ kho",
        "severity": "High",
        "title": "Overflow kiểu Short khi trừ quantity",
        "detail": "ProductVariants.quantity là Short; (short)(qty - n) có thể wrap âm.",
        "steps": "Race condition hoặc quantity edge case",
        "expected": "Exception hoặc reject",
        "actual": "Có thể wrap thành số lớn",
        "files": "CheckoutServiceImpl.java (~278-280); ProductVariants.java",
        "fix": "Dùng Integer; validate không âm sau trừ.",
    },
    {
        "id": "BUG-014",
        "module": "Khuyến mãi / Voucher",
        "feature": "Giới hạn lượt dùng voucher",
        "severity": "High",
        "title": "Race condition vượt quantity voucher",
        "detail": "markUsed() increment không lock; 2 checkout đồng thời có thể dùng voucher lượt cuối.",
        "steps": "Voucher còn 1 lượt, 2 user checkout cùng lúc",
        "expected": "1 thành công",
        "actual": "Cả 2 có thể apply",
        "files": "VoucherServiceImpl.java; VoucherDiscountCalculator.java",
        "fix": "Optimistic/pessimistic lock trên voucher row.",
    },
    {
        "id": "BUG-015",
        "module": "Đăng ký",
        "feature": "Hiển thị lỗi API",
        "severity": "High",
        "title": "RegisterView catch dùng biến api không tồn tại",
        "detail": "catch block: error.value = api.message nhưng không khai báo api → ReferenceError.",
        "steps": "Đăng ký email/username trùng",
        "expected": "Hiện message lỗi từ server",
        "actual": "ReferenceError, UI không báo lỗi đúng",
        "files": "RegisterView.vue (~161-164)",
        "fix": "error.value = getApiError(registerError, 'Đăng ký thất bại').message",
    },
    {
        "id": "BUG-016",
        "module": "Router / Auth",
        "feature": "Navigation guard",
        "severity": "High",
        "title": "Router crash khi localStorage JSON hỏng",
        "detail": "JSON.parse(localStorage user) không try/catch trong beforeEach.",
        "steps": "Sửa sport-store-user thành JSON invalid → navigate",
        "expected": "Redirect login an toàn",
        "actual": "App crash SyntaxError",
        "files": "router/index.js (~132-133)",
        "fix": "safeParse + try/catch như appStore.js.",
    },
    {
        "id": "BUG-017",
        "module": "Auth / API",
        "feature": "Token refresh",
        "severity": "High",
        "title": "Frontend không dùng refresh token",
        "detail": "Access token TTL 15 phút; 401 → logout ngay; /api/auth/refresh có sẵn nhưng không dùng.",
        "steps": "Dùng app > 15 phút, gọi API protected",
        "expected": "Tự refresh token, tiếp tục session",
        "actual": "Bị logout đột ngột",
        "files": "api.js (~46-65); AuthTokenApiController.java",
        "fix": "Interceptor 401 thử refresh trước logout.",
    },
    {
        "id": "BUG-018",
        "module": "Checkout",
        "feature": "Xác nhận đơn",
        "severity": "High",
        "title": "Double-click tạo đơn trùng",
        "detail": "Không idempotency key; double-click 'Xác nhận' gọi confirmCheckout nhiều lần.",
        "steps": "Double-click nút xác nhận đặt hàng nhanh",
        "expected": "Chỉ 1 đơn được tạo",
        "actual": "Có thể tạo nhiều đơn",
        "files": "PaymentView.vue (~512-550)",
        "fix": "Disable button ngay + idempotency key server-side.",
    },
    {
        "id": "BUG-019",
        "module": "Giỏ hàng / Checkout",
        "feature": "Đồng bộ giá",
        "severity": "Medium",
        "title": "Giá giỏ localStorage lệch giá server",
        "detail": "Admin đổi giá sau khi user thêm giỏ; checkout tính giá DB mới không cảnh báo.",
        "steps": "Thêm SP → admin đổi giá → checkout",
        "expected": "Cảnh báo chênh lệch giá",
        "actual": "User thấy tổng khác dự kiến",
        "files": "appStore.js; CheckoutServiceImpl.java",
        "fix": "Re-fetch giá trước checkout hoặc hiển thị diff.",
    },
    {
        "id": "BUG-020",
        "module": "Giỏ hàng",
        "feature": "Tăng/giảm số lượng",
        "severity": "Medium",
        "title": "CartView không giới hạn theo stock",
        "detail": "updateCartQuantity có clamp nhưng UI không hiển thị toast/disable nút +.",
        "steps": "Item stock=5, bấm + nhiều lần",
        "expected": "Dừng ở 5, thông báo",
        "actual": "Có thể hiển thị >5 (clamp im lặng)",
        "files": "CartView.vue (~94-100); appStore.js (~166-185)",
        "fix": "Toast khi clamp; disable + theo stock.",
    },
    {
        "id": "BUG-021",
        "module": "Checkout",
        "feature": "Validate amount client",
        "severity": "Medium",
        "title": "Trường amount client không được server đối chiếu",
        "detail": "CheckoutConfirmRequest có amount nhưng confirmCheckout() không so sánh.",
        "steps": "Gửi amount sai qua DevTools khi confirm",
        "expected": "400 Bad Request",
        "actual": "Server bỏ qua, tính theo DB",
        "files": "CheckoutConfirmRequest.java; CheckoutServiceImpl.java",
        "fix": "So sánh request.amount với total server-side.",
    },
    {
        "id": "BUG-022",
        "module": "Checkout / Voucher",
        "feature": "Tổng đơn tối thiểu",
        "severity": "Medium",
        "title": "Tổng đơn luôn >= 1đ dù voucher 100%",
        "detail": "Logic .max(BigDecimal.ONE) ép tổng tối thiểu 1đ.",
        "steps": "Voucher giảm 100% subtotal + ship",
        "expected": "0đ hoặc thông báo policy rõ",
        "actual": "Luôn >= 1đ",
        "files": "CheckoutServiceImpl.java (~102-104)",
        "fix": "Cho phép 0đ hoặc document policy.",
    },
    {
        "id": "BUG-023",
        "module": "Checkout / Địa chỉ",
        "feature": "Lưu nhãn địa chỉ",
        "severity": "Medium",
        "title": "Logic addressBookLabel đảo ngược khi set default",
        "detail": "setAsDefault=true → gửi addressBookLabel: null.",
        "steps": "Nhập nhãn 'Nhà riêng' + tick đặt mặc định",
        "expected": "Lưu cả nhãn và default",
        "actual": "Nhãn bị null",
        "files": "PaymentView.vue (~451)",
        "fix": "Luôn gửi label nếu user nhập.",
    },
    {
        "id": "BUG-024",
        "module": "Checkout / Địa chỉ",
        "feature": "Validate SĐT",
        "severity": "Medium",
        "title": "Backend không validate định dạng SĐT",
        "detail": "Chỉ @NotBlank + @Size; chấp nhận 'abc'.",
        "steps": "Nhập SĐT 'abc' khi checkout",
        "expected": "400 validation error",
        "actual": "Lưu SĐT không hợp lệ",
        "files": "OrderShippingRequest.java; CheckoutServiceImpl.java",
        "fix": "Regex SĐT VN 10-11 số.",
    },
    {
        "id": "BUG-025",
        "module": "Checkout / Vận chuyển",
        "feature": "Load carriers",
        "severity": "Medium",
        "title": "API carriers fail → không checkout được",
        "detail": "selectedCarrierId null nếu /api/checkout/carriers lỗi.",
        "steps": "Block API carriers, vào payment",
        "expected": "Fallback/retry",
        "actual": "Validation fail vĩnh viễn",
        "files": "PaymentView.vue (~505-509)",
        "fix": "Error state + retry + default carrier.",
    },
    {
        "id": "BUG-026",
        "module": "Khuyến mãi",
        "feature": "Apply voucher",
        "severity": "Medium",
        "title": "Voucher preview và confirm không atomic",
        "detail": "Admin vô hiệu voucher giữa preview và confirm.",
        "steps": "Apply voucher → admin disable → confirm ngay",
        "expected": "Thông báo voucher hết hiệu lực rõ ràng",
        "actual": "Lỗi generic hoặc timing issue",
        "files": "PaymentView.vue; VoucherDiscountCalculator.java",
        "fix": "Re-validate + UX message cụ thể.",
    },
    {
        "id": "BUG-027",
        "module": "Auth / Sản phẩm",
        "feature": "Kiểm tra đăng nhập",
        "severity": "Medium",
        "title": "isLoggedIn không thống nhất giữa các trang",
        "detail": "ProductDetailView check username only; thiếu accessToken.",
        "steps": "Có user localStorage nhưng hết accessToken",
        "expected": "Coi chưa đăng nhập",
        "actual": "Cho thao tác rồi API 401",
        "files": "ProductDetailView.vue (~306); appStore.js (~191)",
        "fix": "Dùng store.isLoggedIn() everywhere.",
    },
    {
        "id": "BUG-028",
        "module": "Quên mật khẩu",
        "feature": "Nhập OTP",
        "severity": "Medium",
        "title": "Frontend chấp nhận OTP 4 ký tự, backend cần 6",
        "detail": "ForgotPasswordView validate length < 4; OtpService length=6.",
        "steps": "Nhập OTP 4 số",
        "expected": "Bắt đủ 6 số",
        "actual": "Gửi request fail không rõ",
        "files": "ForgotPasswordView.vue (~212); OtpService.java",
        "fix": "Validate length === 6 ở FE.",
    },
    {
        "id": "BUG-029",
        "module": "Quên mật khẩu",
        "feature": "Lưu OTP",
        "severity": "Medium",
        "title": "OTP in-memory mất khi restart server",
        "detail": "OtpService dùng ConcurrentHashMap; restart → OTP invalid.",
        "steps": "Gửi OTP → restart Spring Boot → nhập OTP",
        "expected": "OTP vẫn hợp lệ hoặc thông báo rõ",
        "actual": "NOT_FOUND / OTP sai",
        "files": "OtpService.java",
        "fix": "Redis/DB + hash OTP.",
    },
    {
        "id": "BUG-030",
        "module": "Quên mật khẩu",
        "feature": "Gửi OTP email",
        "severity": "Medium",
        "title": "OTP lộ trong server log khi SMTP fail",
        "detail": "log.info in OTP plaintext khi mail không gửi được.",
        "steps": "Request reset khi SMTP chưa cấu hình",
        "expected": "Không log OTP",
        "actual": "OTP trong log file",
        "files": "PasswordResetService.java (~74-75)",
        "fix": "Không log OTP; chỉ devExposeOtp flag.",
    },
    {
        "id": "BUG-031",
        "module": "Chat hỗ trợ",
        "feature": "Gửi tin nhắn WS",
        "severity": "Medium",
        "title": "Tin WS không hiện nếu broadcast fail",
        "detail": "Không optimistic UI; REST fallback chỉ khi WS disconnected.",
        "steps": "WS connected, server lỗi publish",
        "expected": "Hiện lỗi hoặc fallback REST",
        "actual": "Tin biến mất im lặng",
        "files": "FloatingChatWidget.vue (~211-224)",
        "fix": "Optimistic message + REST fallback on error.",
    },
    {
        "id": "BUG-032",
        "module": "Thanh toán / SePay",
        "feature": "Polling trạng thái",
        "severity": "Medium",
        "title": "Polling SePay tối đa ~20 giây",
        "detail": "PaymentResultView poll 8 lần; IPN chậm >20s → UI treo.",
        "steps": "Thanh toán OK nhưng IPN chậm",
        "expected": "Tiếp tục poll hoặc nút kiểm tra lại",
        "actual": "Dừng poll, hiện 'Đang xác nhận' mãi",
        "files": "PaymentResultView.vue (~40, 67-94)",
        "fix": "Tăng poll / nút 'Kiểm tra lại'.",
    },
    {
        "id": "BUG-033",
        "module": "Admin / Chat",
        "feature": "Phân quyền chat",
        "severity": "Medium",
        "title": "Admin chat không có permission riêng",
        "detail": "Route /admin/chat chỉ requiresPanel, không permission code.",
        "steps": "Staff có panel access → vào /admin/chat",
        "expected": "Permission CHAT_VIEW riêng",
        "actual": "Mọi staff vào được chat",
        "files": "router/index.js (~74-78); adminAccess.js",
        "fix": "Thêm ADMIN_PERMS.CHAT.",
    },
    {
        "id": "BUG-034",
        "module": "Giỏ hàng",
        "feature": "Thêm giỏ guest",
        "severity": "Medium",
        "title": "Yêu cầu login thêm giỏ nhưng /cart public",
        "detail": "ProductDetail toast 'đăng nhập'; /cart không requiresAuth.",
        "steps": "Guest thêm giỏ từ chi tiết SP",
        "expected": "Guest cart hoặc redirect login rõ",
        "actual": "Toast lỗi, /cart trống",
        "files": "ProductDetailView.vue; router/index.js (~57)",
        "fix": "Guest cart hoặc redirect + return URL.",
    },
    {
        "id": "BUG-035",
        "module": "Giỏ hàng (Legacy)",
        "feature": "Thêm SP Thymeleaf",
        "severity": "Medium",
        "title": "CartServiceImpl.add() fail im lặng",
        "detail": "if (product == null) return; không throw.",
        "steps": "POST add product ID không tồn tại (Thymeleaf cart)",
        "expected": "Thông báo lỗi",
        "actual": "Im lặng, không thêm",
        "files": "CartServiceImpl.java (~54-57)",
        "fix": "Throw IllegalArgumentException.",
    },
    {
        "id": "BUG-036",
        "module": "Bảo mật / Auth",
        "feature": "JWT secret",
        "severity": "Low",
        "title": "JWT secret mặc định dev nếu không cấu hình",
        "detail": "Fallback secret hardcoded trong JwtService.",
        "steps": "Deploy production không set app.security.jwt.secret",
        "expected": "Fail startup hoặc bắt buộc env",
        "actual": "Dùng secret dev predictable",
        "files": "JwtService.java (~29-48)",
        "fix": "Bắt buộc secret trong production profile.",
    },
    {
        "id": "BUG-037",
        "module": "API Client",
        "feature": "Xử lý 401",
        "severity": "Low",
        "title": "401 interceptor logout toàn cục",
        "detail": "Mọi 401 → logout(); không phân biệt resource vs auth.",
        "steps": "Một API 401 trong lúc nhiều request",
        "expected": "Chỉ fail request liên quan",
        "actual": "Logout toàn session",
        "files": "api.js (~46-65)",
        "fix": "Refresh trước; phân biệt loại 401.",
    },
    {
        "id": "BUG-038",
        "module": "Checkout UI",
        "feature": "Render danh sách item",
        "severity": "Low",
        "title": "Vue key trùng khi variantId null",
        "detail": ":key=\"item.variantId || item.productId\" trùng nếu 2 item cùng product.",
        "steps": "2 dòng cùng productId, variantId null",
        "expected": "Key unique",
        "actual": "Render/state sai",
        "files": "CheckoutView.vue (~22); PaymentView.vue (~195)",
        "fix": "Key composite productId-variantId-index.",
    },
    {
        "id": "BUG-039",
        "module": "Thanh toán / SePay",
        "feature": "Hủy thanh toán",
        "severity": "Low",
        "title": "Cancel SePay: đơn UNPAID, stock không hoàn",
        "detail": "Trang cancel thông báo đơn lưu UNPAID; không restock.",
        "steps": "Tạo đơn SePay → cancel URL",
        "expected": "Hủy đơn + hoàn kho",
        "actual": "Đơn treo UNPAID, stock mất",
        "files": "PaymentResultView.vue; CheckoutServiceImpl.java",
        "fix": "Job auto-cancel UNPAID + restock.",
    },
    {
        "id": "BUG-040",
        "module": "Đăng nhập",
        "feature": "Ghi nhớ đăng nhập",
        "severity": "Low",
        "title": "Checkbox remember-me không hoạt động",
        "detail": "FE gửi remember-me; SecurityConfig rememberMe disabled.",
        "steps": "Tick 'Ghi nhớ đăng nhập'",
        "expected": "Session kéo dài",
        "actual": "Không có tác dụng",
        "files": "api.js; SecurityConfig.java; LoginView.vue",
        "fix": "Bỏ checkbox hoặc implement remember-me/refresh dài.",
    },
]

# Map bug IDs for quick lookup
BUG_IDS = {b["id"] for b in BUGS}

# ---------------------------------------------------------------------------
# TEST CASES
# ---------------------------------------------------------------------------
def tc(tcid, module, feature, name, priority, precond, data, steps, expected, actual="", status="Fail", bug="", note=""):
    return {
        "id": tcid,
        "module": module,
        "feature": feature,
        "name": name,
        "priority": priority,
        "precond": precond,
        "data": data,
        "steps": steps,
        "expected": expected,
        "actual": actual,
        "status": status,
        "bug": bug,
        "note": note,
    }

TEST_CASES = [
    # === TRANG CHỦ & CATALOG ===
    tc("TC-001", "Trang chủ", "Tải trang chủ", "Hiển thị trang chủ đầy đủ section", "P1",
       "Server + FE chạy; DB có dữ liệu",
       "URL: http://localhost:5173/",
       "1. Mở trang chủ\n2. Quan sát Hero, Brand, Best seller, Featured",
       "Tất cả section load; không lỗi console",
       "API /api/public/home gộp 1 request; section hiển thị OK", "Pass", "", "Đã tối ưu gộp API home"),
    tc("TC-002", "Trang chủ", "API Home", "GET /api/public/home trả đủ fields", "P1",
       "Backend port 8080",
       "GET /base/api/public/home",
       "1. Gọi API\n2. Kiểm tra brands, bestSellers, featured",
       "HTTP 200; JSON có brands[], bestSellers[], featured[]",
       "Cấu trúc đúng theo PublicProductServiceImpl.getHomeData()", "Pass", "", ""),
    tc("TC-003", "Sản phẩm", "Danh sách SP", "Lọc theo danh mục", "P1",
       "Có category trong DB",
       "cat=Giày chạy bộ",
       "1. Vào /product\n2. Chọn danh mục\n3. Xem kết quả",
       "Chỉ SP thuộc danh mục; phân trang OK",
       "", "Not Tested", "", "Cần test manual với DB thật"),
    tc("TC-004", "Sản phẩm", "Danh sách SP", "Tìm kiếm keyword", "P1",
       "Có SP Nike trong DB",
       "keyword=Nike",
       "1. Vào /product?keyword=Nike",
       "SP có tên/chứa Nike hiển thị",
       "", "Not Tested", "", ""),
    tc("TC-005", "Sản phẩm", "Danh sách SP", "Lọc giá min-max", "P2",
       "Có SP nhiều mức giá",
       "min=1000000, max=3000000",
       "1. Nhập khoảng giá\n2. Lọc",
       "SP trong khoảng giá; min>max → 400",
       "", "Not Tested", "", ""),
    tc("TC-006", "Sản phẩm", "Chi tiết SP", "Xem chi tiết + gallery + variants", "P1",
       "SP có variants và ảnh",
       "productId hợp lệ",
       "1. Click SP\n2. Xem gallery, chọn size/màu",
       "Hiển thị đúng variant; giá thay đổi theo variant",
       "", "Not Tested", "", ""),
    tc("TC-007", "Sản phẩm", "Giá thành viên", "Hiển thị giá giảm theo hạng", "P1",
       "User có rankDiscountPercent>0",
       "User Silver 10%",
       "1. Login\n2. Xem chi tiết SP\n3. Checkout cùng SP",
       "Giá checkout = giá hiển thị (đã giảm)",
       "FE hiển thị giảm; backend tính giá gốc", "Fail", "BUG-006", ""),
    tc("TC-008", "Sản phẩm", "Thương hiệu", "Trang /brands liệt kê brand", "P2",
       "DB có brand",
       "",
       "1. Vào /brands\n2. Click brand",
       "Danh sách brand; click → lọc SP",
       "", "Not Tested", "", ""),
    tc("TC-009", "Sản phẩm", "Bình luận", "Xem comment public", "P2",
       "SP có comment",
       "GET /api/public/products/{id}/comments",
       "1. Vào chi tiết SP\n2. Xem đánh giá",
       "Hiển thị comment + avg rating",
       "", "Not Tested", "", ""),
    tc("TC-010", "Sản phẩm", "Bình luận", "User gửi comment", "P1",
       "User đã login",
       "rating=5, content=test",
       "1. Login\n2. Gửi đánh giá",
       "Comment lưu; hiển thị sau refresh",
       "", "Not Tested", "", ""),

    # === AUTH ===
    tc("TC-011", "Đăng ký", "Register hợp lệ", "Đăng ký tài khoản mới", "P1",
       "Email/username chưa tồn tại",
       "username=test01, email=test@test.com, password=Test@1234",
       "1. Vào /register\n2. Điền form\n3. Submit",
       "Thành công; redirect login",
       "", "Not Tested", "", ""),
    tc("TC-012", "Đăng ký", "Register trùng email", "Hiển thị lỗi email trùng", "P1",
       "Email đã tồn tại",
       "email trùng",
       "1. Đăng ký email đã có",
       "Message: Email đã được sử dụng",
       "ReferenceError api is not defined", "Fail", "BUG-015", ""),
    tc("TC-013", "Đăng ký", "Validate password", "Password yếu bị từ chối", "P2",
       "",
       "password=123",
       "1. Nhập password yếu\n2. Submit",
       "Hiện lỗi PasswordPolicy",
       "", "Not Tested", "", ""),
    tc("TC-014", "Đăng nhập", "Login JWT", "Đăng nhập username/password", "P1",
       "Account active",
       "username/password hợp lệ",
       "1. /login\n2. Submit",
       "Nhận accessToken + refreshToken; redirect profile",
       "", "Not Tested", "", ""),
    tc("TC-015", "Đăng nhập", "Login sai", "Sai password 5 lần", "P1",
       "",
       "password sai",
       "1. Login sai 5 lần",
       "Rate limit / khóa tạm",
       "", "Not Tested", "", "LoginAttemptService in-memory"),
    tc("TC-016", "Đăng nhập", "Remember me", "Checkbox ghi nhớ", "P3",
       "",
       "remember-me=true",
       "1. Tick ghi nhớ\n2. Login\n3. Đóng browser mở lại",
       "Vẫn đăng nhập",
       "Checkbox không có tác dụng", "Fail", "BUG-040", ""),
    tc("TC-017", "Đăng nhập", "Google OAuth", "Login Google", "P1",
       "OAuth configured",
       "",
       "1. Click Google login\n2. Hoàn tất OAuth",
       "Đăng nhập thành công",
       "Token lộ trong URL hash", "Fail", "BUG-011", ""),
    tc("TC-018", "Đăng nhập", "Guest route", "Guest không vào /profile", "P1",
       "Chưa login",
       "",
       "1. Truy cập /profile",
       "Redirect /login?redirect=/profile",
       "", "Not Tested", "", ""),
    tc("TC-019", "Auth", "Token refresh", "Session > 15 phút vẫn dùng được", "P1",
       "Access TTL 900s",
       "",
       "1. Login\n2. Chờ 16 phút\n3. Gọi API profile",
       "Tự refresh token",
       "Logout đột ngột", "Fail", "BUG-017", ""),
    tc("TC-020", "Auth", "Router guard", "localStorage user corrupt", "P2",
       "",
       "sport-store-user=invalid json",
       "1. Sửa localStorage\n2. Navigate bất kỳ",
       "Redirect login, không crash",
       "JSON.parse throw crash app", "Fail", "BUG-016", ""),

    # === QUÊN MK ===
    tc("TC-021", "Quên MK", "Gửi OTP", "Request reset email hợp lệ", "P1",
       "Email tồn tại; SMTP cấu hình",
       "email=user@test.com",
       "1. /forgot-password\n2. Nhập email\n3. Gửi",
       "Message chung; email nhận OTP 6 số",
       "", "Not Tested", "", ""),
    tc("TC-022", "Quên MK", "Verify OTP", "OTP đúng 6 số", "P1",
       "Đã gửi OTP",
       "otp=6 digits",
       "1. Nhập OTP\n2. Verify",
       "Nhận resetToken",
       "", "Not Tested", "", ""),
    tc("TC-023", "Quên MK", "OTP 4 số", "Frontend reject OTP ngắn", "P2",
       "",
       "otp=1234",
       "1. Nhập 4 số\n2. Submit",
       "Báo cần 6 số",
       "FE cho submit 4 số", "Fail", "BUG-028", ""),
    tc("TC-024", "Quên MK", "Reset password", "Đổi MK với resetToken", "P1",
       "Có resetToken",
       "password mới hợp lệ",
       "1. /reset-password\n2. Submit",
       "Đổi MK OK; login được",
       "", "Not Tested", "", ""),
    tc("TC-025", "Quên MK", "OTP sau restart", "OTP còn hiệu lực sau restart server", "P2",
       "OTP đã gửi",
       "",
       "1. Gửi OTP\n2. Restart backend\n3. Nhập OTP",
       "Thông báo OTP hết hạn rõ",
       "OTP mất im lặng", "Fail", "BUG-029", ""),

    # === GIỎ HÀNG ===
    tc("TC-026", "Giỏ hàng", "Thêm giỏ", "User login thêm SP", "P1",
       "User login; SP còn hàng",
       "qty=1",
       "1. Chi tiết SP\n2. Thêm giỏ",
       "Toast success; badge giỏ tăng",
       "", "Not Tested", "", ""),
    tc("TC-027", "Giỏ hàng", "Thêm giỏ guest", "Guest thêm SP", "P2",
       "Chưa login",
       "",
       "1. Guest click thêm giỏ",
       "Guest cart hoặc redirect login",
       "Toast yêu cầu login", "Fail", "BUG-034", ""),
    tc("TC-028", "Giỏ hàng", "Giỏ theo user", "Đổi user không lẫn giỏ", "P1",
       "2 account trên cùng browser",
       "",
       "1. User A thêm hàng\n2. Logout User B login",
       "Giỏ B riêng/trống",
       "User B thấy giỏ A", "Fail", "BUG-007", ""),
    tc("TC-029", "Giỏ hàng", "Tăng số lượng", "Không vượt stock", "P1",
       "SP stock=5 trong giỏ",
       "",
       "1. Vào /cart\n2. Bấm + nhiều lần",
       "Dừng ở 5; thông báo",
       "Clamp im lặng", "Fail", "BUG-020", ""),
    tc("TC-030", "Giỏ hàng", "Đồng bộ giá", "Admin đổi giá sau thêm giỏ", "P2",
       "SP trong giỏ",
       "",
       "1. Thêm giỏ\n2. Admin đổi giá\n3. Checkout",
       "Cảnh báo chênh lệch",
       "Tổng khác không báo", "Fail", "BUG-019", ""),

    # === CHECKOUT ===
    tc("TC-031", "Checkout", "Flow cơ bản", "Checkout COD thành công", "P1",
       "User login; giỏ có SP; địa chỉ OK",
       "payment=COD",
       "1. /cart/checkout\n2. Nhập địa chỉ\n3. Xác nhận COD",
       "Tạo đơn PENDING/UNPAID; stock trừ",
       "", "Not Tested", "", ""),
    tc("TC-032", "Checkout", "Validate địa chỉ", "SĐT không hợp lệ", "P2",
       "",
       "phone=abc",
       "1. Nhập SĐT abc\n2. Submit",
       "400 validation",
       "Chấp nhận abc", "Fail", "BUG-024", ""),
    tc("TC-033", "Checkout", "Voucher", "Apply voucher hợp lệ", "P1",
       "Voucher active, còn lượt",
       "code=GIAM10",
       "1. Payment page\n2. Nhập voucher\n3. Apply",
       "Giảm đúng; preview total",
       "", "Not Tested", "", ""),
    tc("TC-034", "Checkout", "Voucher 100%", "Tổng đơn sau voucher", "P2",
       "Voucher free 100%",
       "",
       "1. Apply voucher 100%\n2. Confirm",
       "0đ hoặc policy rõ",
       "Luôn >= 1đ", "Fail", "BUG-022", ""),
    tc("TC-035", "Checkout", "Double submit", "Chống double-click confirm", "P1",
       "Giỏ ready",
       "",
       "1. Double-click Xác nhận nhanh",
       "Chỉ 1 đơn",
       "Có thể nhiều đơn", "Fail", "BUG-018", ""),
    tc("TC-036", "Checkout", "Concurrent stock", "2 user mua SP cuối cùng", "P1",
       "Stock=1",
       "",
       "1. 2 tab checkout\n2. Confirm đồng thời",
       "1 success 1 fail",
       "Cả 2 success", "Fail", "BUG-005", ""),
    tc("TC-037", "Checkout", "MoMo payment", "MoMo không auto PAID", "P1",
       "",
       "payment=MOMO",
       "1. Chọn MoMo\n2. Confirm chưa thanh toán thật",
       "paymentStatus=UNPAID",
       "PAID ngay", "Fail", "BUG-001", ""),

    # === SEPAY ===
    tc("TC-038", "SePay", "Tạo đơn", "Redirect cổng SePay", "P1",
       "sepay.enabled=true",
       "payment=SEPAY",
       "1. Chọn SePay\n2. Confirm",
       "Redirect pay.sepay.vn; đơn UNPAID",
       "", "Not Tested", "", ""),
    tc("TC-039", "SePay", "Hủy thanh toán", "Cancel → hoàn stock", "P1",
       "Đơn SePay UNPAID",
       "",
       "1. Tạo đơn SePay\n2. Cancel tại cổng",
       "Hủy đơn + hoàn kho",
       "UNPAID treo, stock mất", "Fail", "BUG-002,BUG-039", ""),
    tc("TC-040", "SePay", "Clear cart", "Giỏ sau cancel SePay", "P1",
       "",
       "",
       "1. Checkout SePay\n2. Cancel",
       "Giỏ còn nguyên",
       "Giỏ bị xóa", "Fail", "BUG-008", ""),
    tc("TC-041", "SePay", "IPN", "Webhook xác nhận PAID", "P1",
       "Thanh toán thành công SePay",
       "",
       "1. Thanh toán\n2. IPN callback",
       "paymentStatus=PAID",
       "", "Not Tested", "", ""),
    tc("TC-042", "SePay", "IPN amount", "IPN sai amount bị reject", "P1",
       "",
       "amount giả",
       "1. Gửi IPN amount sai",
       "Reject, không PAID",
       "Có thể PAID", "Fail", "BUG-003", ""),
    tc("TC-043", "SePay", "Polling", "Trang success poll trạng thái", "P2",
       "IPN chậm >20s",
       "",
       "1. Thanh toán\n2. Chờ >20s",
       "Tiếp tục poll / nút retry",
       "Dừng poll sớm", "Fail", "BUG-032", ""),

    # === PROFILE / WISHLIST / ADDRESS ===
    tc("TC-044", "Profile", "Xem profile", "GET /api/profile", "P1",
       "User login",
       "",
       "1. Vào /profile",
       "Hiển thị thông tin + hạng",
       "", "Not Tested", "", ""),
    tc("TC-045", "Profile", "Đổi MK", "Change password", "P1",
       "",
       "oldPwd, newPwd hợp lệ",
       "1. Tab đổi MK\n2. Submit",
       "Đổi OK; login MK mới",
       "", "Not Tested", "", ""),
    tc("TC-046", "Profile", "Upload avatar", "Upload ảnh Cloudinary", "P2",
       "Cloudinary configured",
       "file jpg <2MB",
       "1. Upload avatar",
       "URL avatar cập nhật",
       "", "Not Tested", "", ""),
    tc("TC-047", "Yêu thích", "Wishlist CRUD", "Thêm/xóa wishlist", "P1",
       "User login",
       "productId",
       "1. Thêm yêu thích\n2. Vào /favorites\n3. Xóa",
       "CRUD OK",
       "", "Not Tested", "", ""),
    tc("TC-048", "Địa chỉ", "Address book", "CRUD địa chỉ giao hàng", "P1",
       "User login",
       "",
       "1. /addresses\n2. Thêm/sửa/xóa/set default",
       "CRUD OK; default đúng 1",
       "", "Not Tested", "", ""),

    # === ORDERS ===
    tc("TC-049", "Đơn hàng", "Lịch sử", "User xem đơn của mình", "P1",
       "User có đơn",
       "",
       "1. Profile tab đơn hàng\n2. Xem chi tiết",
       "Chỉ đơn của user hiện tại",
       "", "Not Tested", "", ""),
    tc("TC-050", "Đơn hàng", "Isolation", "Không xem đơn user khác", "P1",
       "2 user có đơn",
       "orderId user khác",
       "1. Gọi GET /api/orders/{id} đơn người khác",
       "403/404",
       "", "Not Tested", "", ""),

    # === ADMIN ===
    tc("TC-051", "Admin", "Dashboard", "Load thống kê dashboard", "P1",
       "Admin login",
       "",
       "1. /admin/dashboard",
       "Stats + charts hiển thị",
       "", "Not Tested", "", ""),
    tc("TC-052", "Admin", "Phân quyền", "Staff không vào module không có quyền", "P1",
       "Staff thiếu PRODUCT perm",
       "",
       "1. Staff truy cập /admin/product",
       "Redirect fallback",
       "", "Not Tested", "", ""),
    tc("TC-053", "Admin SP", "CRUD sản phẩm", "Thêm/sửa/xóa SP + variant", "P1",
       "Admin PRODUCT perm",
       "",
       "1. /admin/product\n2. CRUD",
       "Lưu DB OK; ảnh upload",
       "", "Not Tested", "", ""),
    tc("TC-054", "Admin DM", "CRUD danh mục", "Quản lý category", "P1",
       "Admin CATEGORY perm",
       "",
       "1. /admin/category\n2. CRUD",
       "OK",
       "", "Not Tested", "", ""),
    tc("TC-055", "Admin User", "Quản lý user", "List/search/update user", "P1",
       "Admin USER perm",
       "",
       "1. /admin/user\n2. Search\n3. Update status",
       "OK",
       "", "Not Tested", "", ""),
    tc("TC-056", "Admin Order", "Xác nhận đơn", "PENDING → CONFIRMED", "P1",
       "Có đơn PENDING",
       "",
       "1. /admin/order\n2. Confirm",
       "Status CONFIRMED",
       "", "Not Tested", "", ""),
    tc("TC-057", "Admin Order", "Giao hàng", "CONFIRMED → SHIPPING → DELIVERED", "P1",
       "",
       "",
       "1. Update trạng thái tuần tự\n2. Nhập tracking",
       "Transition hợp lệ; cộng điểm khi DELIVERED",
       "", "Not Tested", "", ""),
    tc("TC-058", "Admin Order", "Hủy đơn", "Cancel → restock", "P1",
       "Đơn có thể hủy",
       "",
       "1. Cancel đơn",
       "Status CANCELLED; stock hoàn",
       "", "Not Tested", "", ""),
    tc("TC-059", "Admin Báo cáo", "Doanh thu", "Report summary + invoices", "P1",
       "Admin ORDER perm",
       "from/to date",
       "1. /admin/invoices\n2. Lọc ngày",
       "Số liệu khớp DB; phân trang OK",
       "Đã tối ưu query DB-side", "Pass", "", "Fix performance đã apply"),
    tc("TC-060", "Admin Voucher", "CRUD voucher", "Tạo/sửa/toggle voucher", "P1",
       "",
       "",
       "1. /admin/voucher\n2. CRUD",
       "OK",
       "", "Not Tested", "", ""),
    tc("TC-061", "Admin Rank", "Hạng thành viên", "CRUD rank + member count", "P2",
       "",
       "",
       "1. /admin/ranks\n2. CRUD",
       "Member count đúng",
       "", "Not Tested", "", ""),
    tc("TC-062", "Admin Comment", "Kiểm duyệt", "Ẩn/xóa comment", "P2",
       "",
       "",
       "1. /admin/comments\n2. Hide/delete",
       "OK",
       "", "Not Tested", "", ""),

    # === CHAT ===
    tc("TC-063", "Chat", "User gửi tin", "Mở chat + gửi message", "P1",
       "User login",
       "",
       "1. Mở widget chat\n2. Gửi tin",
       "Tin hiển thị; admin nhận",
       "", "Not Tested", "", ""),
    tc("TC-064", "Chat", "Admin reply", "Staff trả lời khách", "P1",
       "Admin login",
       "",
       "1. /admin/chat\n2. Reply",
       "Khách nhận realtime",
       "", "Not Tested", "", ""),
    tc("TC-065", "Chat", "WS security", "Refresh token không connect WS", "P1",
       "",
       "refresh token",
       "1. CONNECT WS với refresh token",
       "Từ chối",
       "Có thể connect", "Fail", "BUG-009", ""),
    tc("TC-066", "Chat", "Admin permission", "Staff không có quyền chat", "P2",
       "Staff không CHAT perm",
       "",
       "1. Truy cập /admin/chat",
       "Từ chối",
       "Staff vào được", "Fail", "BUG-033", ""),

    # === SECURITY ===
    tc("TC-067", "Bảo mật", "JWT", "API admin không token → 401", "P1",
       "",
       "",
       "1. GET /api/admin/dashboard không Authorization",
       "401 Unauthorized",
       "", "Not Tested", "", ""),
    tc("TC-068", "Bảo mật", "JWT", "User token không vào admin API", "P1",
       "User ROLE_USER",
       "",
       "1. Gọi /api/admin/products với user token",
       "403 Forbidden",
       "", "Not Tested", "", ""),
    tc("TC-069", "Bảo mật", "Secrets", "Không commit secret production", "P1",
       "",
       "",
       "1. Review repo/config",
       "Chỉ .example; secret qua env",
       "application.properties có secret plaintext", "Fail", "BUG-004", "Cần rotate secret ngay"),
    tc("TC-070", "Bảo mật", "OAuth token URL", "Token không trong URL", "P1",
       "",
       "",
       "1. Login Google\n2. Check URL bar",
       "Không có token trong URL",
       "Token trong hash", "Fail", "BUG-011", ""),
]

# ---------------------------------------------------------------------------
# EXCEL STYLING
# ---------------------------------------------------------------------------
HEADER_FILL = PatternFill("solid", fgColor="1F4E79")
HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
SUBHEADER_FILL = PatternFill("solid", fgColor="D6E4F0")
SEV_FILL = {
    "Critical": PatternFill("solid", fgColor="FF6B6B"),
    "High": PatternFill("solid", fgColor="FFA94D"),
    "Medium": PatternFill("solid", fgColor="FFE066"),
    "Low": PatternFill("solid", fgColor="B2F2BB"),
}
STATUS_FILL = {
    "Pass": PatternFill("solid", fgColor="C3FAE8"),
    "Fail": PatternFill("solid", fgColor="FFC9C9"),
    "Not Tested": PatternFill("solid", fgColor="E9ECEF"),
}
THIN = Side(style="thin", color="CCCCCC")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
WRAP = Alignment(wrap_text=True, vertical="top")


def style_header(ws, row, cols):
    for c in range(1, cols + 1):
        cell = ws.cell(row=row, column=c)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = BORDER


def auto_width(ws, widths):
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w


def write_sheet_huong_dan(wb):
    ws = wb.active
    ws.title = "Huong dan"
    rows = [
        ["BÁO CÁO TEST CASE - SPORTS4LIFE"],
        [f"Dự án: {PROJECT}"],
        [f"Phiên bản: {VERSION} | Ngày: {TEST_DATE}"],
        [""],
        ["MỤC ĐÍCH", "File này liệt kê test case toàn hệ thống và các lỗi phát hiện qua code review + test logic."],
        ["CÁCH DÙNG", "1. Sheet 'Test Cases': chạy từng TC, điền 'Kết quả thực tế' và 'Trạng thái'\n2. Sheet 'Bug Report': chi tiết lỗi + hướng sửa\n3. Cột Bug liên quan map TC ↔ BUG-ID"],
        ["MÔI TRƯỜNG TEST", "Backend: http://localhost:8080 | Frontend: http://localhost:5173 | DB: SQL Server Sports4Life"],
        ["TÀI KHOẢN GỢI Ý", "Admin/Staff/User — dùng account có trong DB ntn.sql hoặc tạo mới qua /register"],
        ["TRẠNG THÁI", "Pass = OK | Fail = lỗi (xem Bug Report) | Not Tested = chưa chạy manual (cần DB + server)"],
        ["MỨC ĐỘ LỖI", "Critical > High > Medium > Low — ưu tiên sửa Critical/High trước production"],
        ["THỐNG KÊ", f"Tổng test case: {len(TEST_CASES)} | Tổng bug: {len(BUGS)} | Fail (code review): {sum(1 for t in TEST_CASES if t['status']=='Fail')}"],
        [""],
        ["MODULES ĐƯỢC TEST", "Trang chủ, Sản phẩm, Auth, Quên MK, Giỏ hàng, Checkout, SePay, Profile, Wishlist, Địa chỉ, Đơn hàng, Admin (Dashboard/SP/DM/User/Order/Báo cáo/Voucher/Rank/Comment), Chat, Bảo mật"],
    ]
    for r, row in enumerate(rows, 1):
        for c, val in enumerate(row, 1):
            cell = ws.cell(row=r, column=c, value=val)
            cell.alignment = WRAP
            if r == 1:
                cell.font = Font(bold=True, size=14)
    ws.column_dimensions["A"].width = 22
    ws.column_dimensions["B"].width = 90


def write_sheet_test_cases(wb):
    ws = wb.create_sheet("Test Cases")
    headers = [
        "TC_ID", "Phân hệ", "Chức năng", "Tên test case", "Ưu tiên",
        "Điều kiện tiên quyết", "Dữ liệu test", "Các bước thực hiện",
        "Kết quả mong đợi", "Kết quả thực tế", "Trạng thái", "Bug liên quan", "Ghi chú",
    ]
    ws.append(headers)
    style_header(ws, 1, len(headers))
    ws.freeze_panes = "A2"

    for t in TEST_CASES:
        ws.append([
            t["id"], t["module"], t["feature"], t["name"], t["priority"],
            t["precond"], t["data"], t["steps"], t["expected"],
            t["actual"], t["status"], t["bug"], t["note"],
        ])

    for row in range(2, ws.max_row + 1):
        status = ws.cell(row=row, column=11).value
        fill = STATUS_FILL.get(status)
        for col in range(1, len(headers) + 1):
            cell = ws.cell(row=row, column=col)
            cell.alignment = WRAP
            cell.border = BORDER
            if col == 11 and fill:
                cell.fill = fill

    auto_width(ws, [10, 16, 18, 32, 8, 24, 18, 36, 28, 28, 12, 14, 20])


def write_sheet_bugs(wb):
    ws = wb.create_sheet("Bug Report")
    headers = [
        "BUG_ID", "Phân hệ", "Chức năng lỗi", "Mức độ", "Tiêu đề lỗi",
        "Mô tả chi tiết", "Các bước tái hiện", "Kết quả mong đợi", "Kết quả thực tế",
        "File/Code liên quan", "Hướng sửa đề xuất", "Trạng thái", "Người sửa", "Ngày sửa",
    ]
    ws.append(headers)
    style_header(ws, 1, len(headers))
    ws.freeze_panes = "A2"

    for b in BUGS:
        ws.append([
            b["id"], b["module"], b["feature"], b["severity"], b["title"],
            b["detail"], b["steps"], b["expected"], b["actual"],
            b["files"], b["fix"], "Open", "", "",
        ])

    for row in range(2, ws.max_row + 1):
        sev = ws.cell(row=row, column=4).value
        fill = SEV_FILL.get(sev)
        for col in range(1, len(headers) + 1):
            cell = ws.cell(row=row, column=col)
            cell.alignment = WRAP
            cell.border = BORDER
            if col == 4 and fill:
                cell.fill = fill

    auto_width(ws, [10, 18, 22, 10, 32, 40, 36, 24, 24, 36, 40, 10, 12, 12])


def write_sheet_summary(wb):
    ws = wb.create_sheet("Tong hop")
    ws.append(["Module", "Tổng TC", "Pass", "Fail", "Not Tested", "Bug Critical", "Bug High", "Bug Medium", "Bug Low"])
    style_header(ws, 1, 9)

    modules = sorted(set(t["module"] for t in TEST_CASES) | set(b["module"] for b in BUGS))
    for mod in modules:
        tcs = [t for t in TEST_CASES if t["module"] == mod]
        bugs = [b for b in BUGS if b["module"] == mod]
        ws.append([
            mod,
            len(tcs),
            sum(1 for t in tcs if t["status"] == "Pass"),
            sum(1 for t in tcs if t["status"] == "Fail"),
            sum(1 for t in tcs if t["status"] == "Not Tested"),
            sum(1 for b in bugs if b["severity"] == "Critical"),
            sum(1 for b in bugs if b["severity"] == "High"),
            sum(1 for b in bugs if b["severity"] == "Medium"),
            sum(1 for b in bugs if b["severity"] == "Low"),
        ])

    ws.append([])
    ws.append(["TỔNG", len(TEST_CASES),
               sum(1 for t in TEST_CASES if t["status"] == "Pass"),
               sum(1 for t in TEST_CASES if t["status"] == "Fail"),
               sum(1 for t in TEST_CASES if t["status"] == "Not Tested"),
               sum(1 for b in BUGS if b["severity"] == "Critical"),
               sum(1 for b in BUGS if b["severity"] == "High"),
               sum(1 for b in BUGS if b["severity"] == "Medium"),
               sum(1 for b in BUGS if b["severity"] == "Low")])

    auto_width(ws, [22, 10, 8, 8, 12, 14, 10, 12, 10])


def main():
    wb = Workbook()
    write_sheet_huong_dan(wb)
    write_sheet_test_cases(wb)
    write_sheet_bugs(wb)
    write_sheet_summary(wb)
    import os
    out_path = os.path.join(os.path.dirname(__file__), OUTPUT)
    wb.save(out_path)
    print(f"Created: {out_path}")
    print(f"Test cases: {len(TEST_CASES)} | Bugs: {len(BUGS)}")


if __name__ == "__main__":
    main()
